"""
Phase 10 Part A: Multi-Language (English & Tamil) Translation Resource.
Provides structured translation dictionaries for report titles, status labels, headers, and disclaimers.
"""
from typing import Dict, Any

TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "en": {
        "report_title": "DiaCare Medical Laboratory Analysis Report",
        "patient_summary_title": "DiaCare Patient Longitudinal Medical Summary",
        "facility_label": "Facility / Lab",
        "date_label": "Report Date",
        "patient_label": "Patient Name",
        "status_label": "Status",
        "test_name_header": "Test Name",
        "value_header": "Measured Value",
        "reference_header": "Reference Range",
        "status_header": "Status",
        "status_high": "HIGH",
        "status_low": "LOW",
        "status_normal": "NORMAL",
        "status_borderline": "BORDERLINE",
        "risk_flags_title": "Clinical Risk Pattern Flags",
        "recommendations_title": "Personalized Recommendations",
        "disclaimer_title": "Medical Disclaimer",
        "disclaimer_text": "This report is generated by DiaCare as a clinical decision support tool and screening aid. It is NOT a direct medical diagnosis. Please consult a licensed physician for clinical evaluation.",
        "demographics_adjusted": "Adjusted for Demographics",
        "general_adult": "General Adult",
    },
    "ta": {
        "report_title": "டியா கேர் மருத்துவ ஆய்வகப் பகுப்பாய்வு அறிக்கை",
        "patient_summary_title": "டியா கேர் நோயாளி மருத்துவ வரலாற்று சுருக்கம்",
        "facility_label": "ஆய்வகத்தின் பெயர்",
        "date_label": "அறிக்கை நாள்",
        "patient_label": "நோயாளி பெயர்",
        "status_label": "நிலை",
        "test_name_header": "பரிசோதனை பெயர்",
        "value_header": "அளவிடப்பட்ட மதிப்பு",
        "reference_header": "இயல்பு அளவு எல்லை",
        "status_header": "நிலை",
        "status_high": "உயர் (HIGH)",
        "status_low": "குறைவு (LOW)",
        "status_normal": "இயல்பு (NORMAL)",
        "status_borderline": "எல்லைக்கோடு (BORDERLINE)",
        "risk_flags_title": "மருத்துவ அபாயக் குறியீடுகள்",
        "recommendations_title": "பரிந்துரைகள் மற்றும் வழிகாட்டுதல்",
        "disclaimer_title": "மருத்துவ நிபந்தனை எச்சரிக்கை",
        "disclaimer_text": "இந்த அறிக்கை டியா கேர் அமைப்பால் மருத்துவ உதவிக்காக உருவாக்கப்பட்டது. இது நேரடி மருத்துவக் கண்டறிதல் அல்ல. தகுதியான மருத்துவரை அணுகவும்.",
        "demographics_adjusted": "வயது/பாலின அடிப்படையில் சீரமைக்கப்பட்டது",
        "general_adult": "பொதுவான பெரியவர்",
    },
}

TEST_NAME_TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "Hemoglobin": {"en": "Hemoglobin", "ta": "ஹீமோகுளோபின் (Hemoglobin)"},
    "Fasting Glucose": {"en": "Fasting Glucose", "ta": "வெறும் வயிற்று சர்க்கரை (Fasting Glucose)"},
    "HbA1c": {"en": "HbA1c", "ta": "எச்பிஏ1சி (HbA1c)"},
    "Total Cholesterol": {"en": "Total Cholesterol", "ta": "மொத்த கொழுப்பு (Total Cholesterol)"},
    "LDL Cholesterol": {"en": "LDL Cholesterol", "ta": "எல்டிஎல் கெட்ட கொழுப்பு (LDL)"},
    "HDL Cholesterol": {"en": "HDL Cholesterol", "ta": "எச்டிஎல் நல்ல கொழுப்பு (HDL)"},
    "Triglycerides": {"en": "Triglycerides", "ta": "ட்ரைபிளிசரைடுகள் (Triglycerides)"},
    "Creatinine": {"en": "Creatinine", "ta": "கிரியேட்டினின் (Creatinine)"},
    "eGFR": {"en": "eGFR", "ta": "சிறுநீரக வடிகட்டும் திறன் (eGFR)"},
    "TSH": {"en": "TSH", "ta": "தைராய்டு ஹார்மோன் (TSH)"},
    "ALT (SGPT)": {"en": "ALT (SGPT)", "ta": "ஏஎல்டி கல்லீரல் என்சைம் (ALT)"},
    "AST (SGOT)": {"en": "AST (SGOT)", "ta": "ஏஎஸ்டி கல்லீரல் என்சைம் (AST)"},
    "GGT": {"en": "GGT", "ta": "ஜிஜிடி (GGT)"},
    "Potassium": {"en": "Potassium", "ta": "பொட்டாசியம் (Potassium)"},
    "Sodium": {"en": "Sodium", "ta": "சோடியம் (Sodium)"},
    "WBC": {"en": "WBC", "ta": "வெள்ளை ரத்த அணுக்கள் (WBC)"},
    "RBC": {"en": "RBC", "ta": "சிவப்பு ரத்த அணுக்கள் (RBC)"},
    "Platelets": {"en": "Platelets", "ta": "ரத்த தட்டுகள் (Platelets)"},
}


def get_translation(key: str, lang: str = "en") -> str:
    """Returns translated string for a given resource key and language ('en' or 'ta')."""
    clean_lang = lang.lower().strip() if lang else "en"
    if clean_lang not in TRANSLATIONS:
        clean_lang = "en"
    return TRANSLATIONS[clean_lang].get(key, TRANSLATIONS["en"].get(key, key))


def get_translated_test_name(test_name: str, lang: str = "en") -> str:
    """Returns translated test name for a given test name and language ('en' or 'ta')."""
    clean_lang = lang.lower().strip() if lang else "en"
    if clean_lang == "ta" and test_name in TEST_NAME_TRANSLATIONS:
        return TEST_NAME_TRANSLATIONS[test_name]["ta"]
    return test_name
